# -*- coding: utf-8 -*-
"""url

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HcGEmoBy0cNOpjERMX3TMlQCsB2As7TM
"""

from urllib.parse import urlparse

def rustore_get_urn(url):

    if "://" in url:
        return url.split("://")[1]
    return url

def rustore_get_domain(url):
    url_parsed = urlparse(url)
    return url_parsed.netloc

def rustore_get_absolute_url(url=None, origin_url=None):
    url = url.lstrip("/")
    url = url.lstrip("./")
    url_parsed = urlparse(origin_url)
    scheme = url_parsed.scheme
    host = url_parsed.netloc
    if "://" in url:
        return url
    else:
        url = "{}://{}/{}".format(scheme, host, url)
        return url