# -*- coding: utf-8 -*-
"""validators

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HcGEmoBy0cNOpjERMX3TMlQCsB2As7TM
"""

def rustore_validate_extractor(extractor):
    validation_errors = []

    extractor_id = extractor.get("extractor_id")
    if extractor_id is None:
        validation_errors.append(f"extractor_id cannot be None in extractor {extractor}")

    extractor_type = extractor.get("extractor_type")
    if extractor_type is None:
        validation_errors.append(f"extractor_type cannot be None in extractor {extractor}")

    return validation_errors