# -*- coding: utf-8 -*-
"""links

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HcGEmoBy0cNOpjERMX3TMlQCsB2As7TM
"""

from rustore.extractors.base import ExtractorBase, ContentExtractorBase
from rustore.utils.url import get_urn, get_domain


class RuStoreAllLinksExtractor(ExtractorBase):
    def run(self):
        data = {}
        extracted_data = []
        links = self.html_selector.css("a").xpath("@href").extract()

        for link in links:
            if link and not link.startswith("#"):
                extracted_data.append(link)
        data[self.extractor_id] = extracted_data
        return data


class RuStoreAllLinksAnalyticsExtractor(ContentExtractorBase):

    def run(self):
        data = {}
        extracted_data = RuStoreAllLinksExtractor(
            url=self.url,
            html_selector=self.html_selector,
            extractor=self.extractor,
            extractor_id="all_links"
        ).run().get("all_links", {})

        links_data = {}
        for link in extracted_data:
            domain = get_domain(link)
            if domain in links_data.keys():
                links_data[domain].append(link)
            else:
                links_data[domain] = [link]

        data[self.extractor_id] = [{"domain": domain, "links": domain_links, "links_count": len(domain_links)} for
                                   domain, domain_links in links_data.items()]

        return data


class RuStoreSameDomainLinkExtractor(ExtractorBase):
    pass


class RuStoreForeignDomainLinkExtractor(ExtractorBase):
    pass


class RuStoreCustomLinkExtractor(ExtractorBase):
    pass